/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bobbyjam99' at '16/03/01 0:05' with Gradle 2.2.1
 *
 * @author bobbyjam99, @date 16/03/01 0:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
